<?php
$page=$_GET["page"]??"dashboard";
$pages=["dashboard"=>"Visão geral","alunos"=>"Alunos","agendamento"=>"Agendamento","estudo"=>"Estudo de Caso","paee"=>"PAEE","pae"=>"PAE","usuarios"=>"Usuários"];
if(!isset($pages[$page]))$page="dashboard";
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AEE • <?=htmlspecialchars($pages[$page])?></title><link rel="stylesheet" href="assets/css/style.css"></head><body>
<div class="app"><aside class="sidebar" id="sidebar">
<div class="logo">AEE</div><div class="subtitle">Atendimento Especializado</div>
<nav>
<a class="<?=($page=="dashboard"?"active":"")?>" href="?page=dashboard">⌂ <span>Início</span></a>
<a class="<?=($page=="alunos"?"active":"")?>" href="?page=alunos">◉ <span>Alunos</span></a>
<a class="<?=($page=="agendamento"?"active":"")?>" href="?page=agendamento">▣ <span>Agendamento</span></a>
<a class="<?=($page=="estudo"?"active":"")?>" href="?page=estudo">▤ <span>Estudo de Caso</span></a>
<a class="<?=($page=="paee"?"active":"")?>" href="?page=paee">◆ <span>PAEE</span></a>
<a class="<?=($page=="pae"?"active":"")?>" href="?page=pae">◇ <span>PAE</span></a>
<div class="label">Administração</div><a class="<?=($page=="usuarios"?"active":"")?>" href="?page=usuarios">♙ <span>Usuários</span></a>
</nav><div class="user">AS · Administrador<br><small>Gestão</small></div></aside>
<main><header><button class="toggle" onclick="toggleMenu()">☰</button><div><small>SISTEMA AEE</small><h1><?=$pages[$page]?></h1></div><div class="user-top">AS &nbsp; Administrador</div></header><section class="content">
<?php if($page=="dashboard"): ?>
<div class="hero"><div><b>Acompanhamento especializado</b><h2>Olá! Seja bem-vindo ao AEE.</h2><p>Centralize os atendimentos, estudos de caso e planos dos alunos.</p></div><a class="btn orange" href="?page=agendamento">+ Novo agendamento</a></div>
<div class="stats"><div><span>Alunos cadastrados</span><strong>128</strong><small>+8 este mês</small></div><div><span>Atendimentos hoje</span><strong>12</strong><small>4 pendentes</small></div><div><span>PAEE ativos</span><strong>74</strong><small>5 atualizados hoje</small></div><div><span>PAE em acompanhamento</span><strong>61</strong><small>3 novos registros</small></div></div>
<div class="columns"><article class="card"><h3>Próximos atendimentos</h3><p>Agenda de hoje</p><div class="item"><b>08:30</b><span><strong>Maria Eduarda Silva</strong>Atendimento individual • 7º A</span><i>Confirmado</i></div><div class="item"><b>10:00</b><span><strong>João Pedro Santos</strong>Acompanhamento • 8º B</span><i class="pending">Pendente</i></div><div class="item"><b>14:30</b><span><strong>Ana Clara Oliveira</strong>Orientação • 9º A</span><i>Confirmado</i></div></article>
<article class="card"><h3>Acesso rápido</h3><p>Principais funções</p><div class="quick"><a href="?page=alunos">◉<strong>Pesquisar aluno</strong><small>Encontrar cadastro</small></a><a href="?page=estudo">▤<strong>Estudo de Caso</strong><small>Consultar registros</small></a><a href="?page=paee">◆<strong>PAEE</strong><small>Planejamento</small></a><a href="?page=pae">◇<strong>PAE</strong><small>Acompanhamento</small></a></div></article></div>
<?php elseif($page=="alunos"): ?>
<article class="card"><div class="head"><div><h3>Cadastro de alunos</h3><p>Pesquise e acesse o perfil de cada aluno.</p></div><button class="btn orange">+ Novo aluno</button></div><div class="filters"><input placeholder="🔎 Buscar por nome ou matrícula"><select><option>Todas as turmas</option></select><select><option>Todos os cursos</option></select></div><table><thead><tr><th>Aluno</th><th>Matrícula</th><th>Idade</th><th>Turma</th><th>Curso</th><th>Status</th></tr></thead><tbody>
<tr><td><strong>Maria Eduarda Silva</strong><small>maria@example.com</small></td><td>2026-001</td><td>13</td><td>7º A</td><td>Fundamental</td><td><i>Ativo</i></td></tr>
<tr><td><strong>João Pedro Santos</strong><small>joao@example.com</small></td><td>2026-002</td><td>14</td><td>8º B</td><td>Fundamental</td><td><i>Ativo</i></td></tr></tbody></table></article>
<?php elseif($page=="agendamento"): ?>
<div class="columns"><article class="card"><h3>Novo agendamento</h3><p>Cadastre um atendimento para o aluno.</p><form onsubmit="save(event)"><label>Aluno<select required><option>Maria Eduarda Silva</option><option>João Pedro Santos</option></select></label><div class="two"><label>Data<input type="date" required></label><label>Horário<input type="time" required></label></div><div class="two"><label>Turma<select><option>7º A</option><option>8º B</option></select></label><label>Curso<input value="Ensino Fundamental"></label></div><label>Tipo<select><option>Atendimento individual</option><option>Acompanhamento</option><option>Orientação</option></select></label><label>Observação<textarea placeholder="Digite uma observação..."></textarea></label><button class="btn orange">Salvar agendamento</button></form></article><article class="card"><h3>Agenda do dia</h3><p>Atendimentos cadastrados</p><div class="item"><b>08:30</b><span><strong>Maria Eduarda Silva</strong>Atendimento individual</span><i>Confirmado</i></div><div class="item"><b>10:00</b><span><strong>João Pedro Santos</strong>Acompanhamento</span><i class="pending">Pendente</i></div></article></div>
<?php elseif($page=="estudo"): ?>
<article class="card"><h3>Estudo de Caso</h3><p>Selecione um aluno para consultar e editar as informações.</p><div class="filters"><input placeholder="🔎 Filtrar por aluno"></div><div class="students"><a href="#dados"><strong>Maria Eduarda Silva</strong><span>7º A • Matrícula 2026-001 →</span></a><a href="#dados"><strong>João Pedro Santos</strong><span>8º B • Matrícula 2026-002 →</span></a></div></article>
<article class="card" id="dados"><div class="head"><div><b class="tag">Aluno selecionado</b><h3>Maria Eduarda Silva</h3><p>7º A • Ensino Fundamental</p></div><button class="btn green" onclick="save(event)">Salvar alterações</button></div><div class="two"><label>Motivo do acompanhamento<textarea>Registro inicial do acompanhamento.</textarea></label><label>Preferências do aluno<textarea>Espaços de estudo tranquilos e atividades com apoio visual.</textarea></label></div><label>Observações e informações<textarea class="big">Área para registrar e editar o estudo de caso.</textarea></label>
<div class="attachments"><div class="head"><div><h3>Documentos do aluno</h3><p>Anexe aqui os documentos relacionados ao Estudo de Caso.</p></div><button class="btn orange" onclick="document.getElementById('files').click()">+ Anexar arquivo</button><input id="files" type="file" multiple hidden></div><div class="files"><div>🧩 <strong>Anamnese</strong><small>PDF, DOC ou DOCX</small></div><div>🧩 <strong>Laudo</strong><small>PDF, DOC ou DOCX</small></div><div>🧩 <strong>Relatórios</strong><small>PDF, DOC ou DOCX</small></div><div>🧩 <strong>Testes</strong><small>PDF, DOC ou DOCX</small></div><div>🧩 <strong>Recomendações e combinados</strong><small>PDF, DOC ou DOCX</small></div></div></div></article>
<?php elseif($page=="paee"): ?>
<article class="card"><h3>PAEE</h3><p>Pesquise o aluno para acessar seu plano.</p><div class="filters"><input placeholder="🔎 Filtrar por aluno"><select><option>Todas as turmas</option></select></div><div class="students"><a href="#paee"><strong>Maria Eduarda Silva</strong><span>7º A • PAEE ativo</span><i>Ativo</i></a><a href="#paee"><strong>João Pedro Santos</strong><span>8º B • PAEE ativo</span><i>Ativo</i></a></div></article><article class="card" id="paee"><div class="head"><div><b class="tag">PAEE • Maria Eduarda Silva</b><h3>Plano de Atendimento Educacional Especializado</h3></div><button class="btn green" onclick="save(event)">Salvar</button></div><div class="two"><label>Objetivos<textarea>Desenvolver autonomia e participação.</textarea></label><label>Necessidades identificadas<textarea>Apoio na organização das atividades.</textarea></label></div><label>Estratégias e recursos<textarea class="big">Utilização de apoio visual, organização por etapas e acompanhamento individual.</textarea></label></article>
<?php elseif($page=="pae"): ?>
<article class="card"><h3>PAE</h3><p>Acompanhamento colaborativo por aluno.</p><div class="filters"><input placeholder="🔎 Filtrar por aluno"></div><div class="students"><a href="#pae"><strong>Maria Eduarda Silva</strong><span>7º A • Última atualização hoje</span><i>Em acompanhamento</i></a></div></article><article class="card" id="pae"><div class="head"><div><b class="tag">PAE • Maria Eduarda Silva</b><h3>Acompanhamento colaborativo</h3><p>Professores e Gestão autorizados podem contribuir.</p></div><button class="btn orange" onclick="save(event)">Adicionar registro</button></div><label>Metas<textarea>Registrar metas e ações definidas pela equipe.</textarea></label><label>Observações<textarea class="big">Área colaborativa para acompanhamento do aluno.</textarea></label><div class="history"><strong>Administrador (Gestão)</strong><small>Atualizou o acompanhamento • Hoje, 09:15</small><hr><strong>Professor Ana</strong><small>Adicionou uma observação • Ontem, 14:30</small></div></article>
<?php else: ?>
<article class="card"><div class="head"><div><h3>Usuários</h3><p>Gerencie os acessos ao sistema.</p></div><button class="btn orange">+ Novo usuário</button></div><table><thead><tr><th>Usuário</th><th>Perfil</th><th>E-mail</th><th>Status</th></tr></thead><tbody><tr><td><strong>Administrador</strong></td><td>Administrador</td><td>admin@aee.local</td><td><i>Ativo</i></td></tr><tr><td><strong>Professor Ana</strong></td><td>Professor</td><td>ana@aee.local</td><td><i>Ativo</i></td></tr><tr><td><strong>Gestão</strong></td><td>Gestão</td><td>gestao@aee.local</td><td><i>Ativo</i></td></tr></tbody></table></article>
<?php endif; ?></section></main></div><div id="toast">Alterações salvas com sucesso.</div><script src="assets/js/app.js"></script></body></html>